[plugin]
name = "Launcher"
description = "Universal search with action modifiers"
version = "0.1.0"
author = "KMRH47"

[daemon]
enabled = true
command = "launcher"

[menu]
label = "Launcher"
items = [
    { type = "action", id = "open", label = "Open Launcher", action = "run" },
]

[[dependencies.binaries]]
name = "launcher"
repo = "qol-tools/plugin-launcher"
pattern = "launcher-{os}-{arch}"
